<?php


namespace app\club\controller;


use app\common\lib\exception\ApiException;
use app\common\model\Club;
use think\Controller;
use think\Request;

class AuthBase extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $isLogin = $this->isLogin();
        if(!$isLogin){
            throw new ApiException('您没有登录');
        }
    }

    public function isLogin(){
        $token = Request::instance()->header('token');
        if(empty($token)){
            return false;
        }
//        $token = $this->headers(['access_user_token']);
        $club = Club::get(['token'  =>  $token]);
        if(time() > $club['time_out']){
            return false;
        }
        return true;
    }

}